version: '3.9'
services:
  db:
    container_name: postgres
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    volumes: 
      - db-store:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/init.sql
  # pgadmin:
  #   container_name: pgadmin4
  #   image: dpage/pgadmin4:7.8
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   ports:
  #     - "5050:80"
  #   volumes:
  #     - pgadmin:/var/lib/pgadmin
volumes:
  db-store:
  # pgadmin:
