// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Todo struct {
	ID          int32            `json:"id"`
	Title       string           `json:"title"`
	CreatedTime pgtype.Timestamp `json:"created_time"`
	UpdatedTime pgtype.Timestamp `json:"updated_time"`
}
