// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: query.sql

package sqlc

import (
	"context"
)

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos (title, created_time, updated_time)
VALUES ($1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, title, created_time, updated_time
`

type CreateTodoParams struct {
	Title string `json:"title"`
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (*Todo, error) {
	row := q.db.QueryRow(ctx, createTodo, arg.Title)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatedTime,
		&i.UpdatedTime,
	)
	return &i, err
}

const deleteAllTodos = `-- name: DeleteAllTodos :exec
DELETE FROM todos
`

func (q *Queries) DeleteAllTodos(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllTodos)
	return err
}

const deleteTodoByID = `-- name: DeleteTodoByID :exec
DELETE FROM todos
WHERE id = $1
`

type DeleteTodoByIDParams struct {
	ID int32 `json:"id"`
}

func (q *Queries) DeleteTodoByID(ctx context.Context, arg DeleteTodoByIDParams) error {
	_, err := q.db.Exec(ctx, deleteTodoByID, arg.ID)
	return err
}

const getAllTodos = `-- name: GetAllTodos :many
SELECT id, title, created_time, updated_time
FROM todos
`

func (q *Queries) GetAllTodos(ctx context.Context) ([]*Todo, error) {
	rows, err := q.db.Query(ctx, getAllTodos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CreatedTime,
			&i.UpdatedTime,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTodoByID = `-- name: GetTodoByID :one
SELECT id, title, created_time, updated_time
FROM todos
WHERE id = $1
`

type GetTodoByIDParams struct {
	ID int32 `json:"id"`
}

func (q *Queries) GetTodoByID(ctx context.Context, arg GetTodoByIDParams) (*Todo, error) {
	row := q.db.QueryRow(ctx, getTodoByID, arg.ID)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatedTime,
		&i.UpdatedTime,
	)
	return &i, err
}

const updateTodo = `-- name: UpdateTodo :one
UPDATE todos
SET title = $1, updated_time = CURRENT_TIMESTAMP
WHERE id = $2
RETURNING id, title, created_time, updated_time
`

type UpdateTodoParams struct {
	Title string `json:"title"`
	ID    int32  `json:"id"`
}

func (q *Queries) UpdateTodo(ctx context.Context, arg UpdateTodoParams) (*Todo, error) {
	row := q.db.QueryRow(ctx, updateTodo, arg.Title, arg.ID)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatedTime,
		&i.UpdatedTime,
	)
	return &i, err
}
