// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Todo struct {
	ID          int32
	Title       pgtype.Text
	CreatedTime pgtype.Timestamp
	UpdatedTime pgtype.Timestamp
}
